simplify rpc logic

diff --git a/bin/seth-rpc b/bin/seth-rpc
--- a/bin/seth-rpc
+++ b/bin/seth-rpc
@@ -1,18 +1,32 @@
 #!/usr/bin/env bash
-set -e -o pipefail; shopt -s lastpipe
-[[ $DEBUG ]] && set -x
-: ${ETH_RPC_URL:=${ETH_RPC_HOST-localhost}:${ETH_RPC_PORT-8545}}
+request=`seth rpc-request "$1" -- "${@:2}"`
+response=`echo "$request" | seth rpc-curl`
 
-seth rpc-signature $1 | read types
-seth rpc-print $1 "$types" "${@:2}" |
-seth rpc-send $ETH_RPC_URL |
-if [[ $RAW ]]; then
-  cat
-else
-  result=$(seth rpc-parse)
-  if [[ $SETH_DECIMAL ]]; then
-    seth to-dec "$result"
-  else
-    echo "$result"
-  fi
+if ! result=`echo "$response" | jshon -Q -e result -j`; then
+  echo "$response" | jshon -Q -e error -j
+  exit 1
 fi
+
+case $result in
+  \"*\") result=`echo "[$result]" | jshon -a -u`;;
+  \[*\]) result=`echo "$result" | jshon -a -j | while read -r entry; do
+    if [[ $entry = \"*\" ]]; then
+      echo "[$entry]" | jshon -a -u
+    else
+      echo "$entry"
+    fi
+  done`;;
+  \{*\}) result=`echo "$result" | jshon -k | while read -r key; do
+    value=$(echo "$result" | jshon -e "$key" -j)
+    if [[ $value = \"*\" ]]; then
+      value=$(echo "[$value]" | jshon -a -u)
+    fi
+    printf "%-23s %s\n" "$key" "$value"
+  done`;;
+esac
+
+if [[ $result = 0x* && ${#result} -lt 20 ]]; then
+  result=$((result))
+fi
+
+echo "$result"
