add double dashes to internal commands, lots more

diff --git a/bin/seth b/bin/seth
--- a/bin/seth
+++ b/bin/seth
@@ -9,64 +9,61 @@
 ###    -p, --rpc-port=<number>    RPC endpoint port (default: `8545')
 ###    -u, --rpc-url=<url>        RPC endpoint URL (overrides `-h' and `-p')
 opts+=(h:p:u:)
-optl+=(rpc-host:rpc-port:rpc-url:)
+optl+=(rpc-host:,rpc-port:,rpc-url:,)
 ###
-### Common options:
+### Transaction options:
 ###
-###    -f, --from=<account>       account to use or send transaction from
+###    -f, --from=<account>       account to use or to send transaction from
 ###    -g, --gas=<number>         number of units of gas to provide
 ###        --gas-price=<money>    price of each gas unit (e.g. `20 Gwei')
 ###    -v, --value=<money>        amount of value to send (e.g. `0.1 ETH')
+opts+=(f:g:v:)
+optl+=(from:,gas:,gas-price:,value:,)
+###
+### Local transaction options:
+###
 ###    -b, --block=<number>       block number (e.g. `985000' or `latest')
-opts+=(f:b:g:v:)
-optl+=(from:block:gas:gas-price:value)
+opts+=(b:)
+optl+=(block:,)
 
 set -e
-args=$(getopt -n ${0##*/} -o "${opts[*]}" -l "${optl[*]}" -- "$@")
-eval set -- $args
+program-exists() { which $1 &>/dev/null; }
 
-while [[ $1 ]]; do
-  case $1 in
-    --)              shift; break;;
-
-    -h|--rpc-host)   shift; export SETH_RPC_HOST=$1;;
-    -p|--rpc-port)   shift; export SETH_RPC_PORT=$1;;
-    -u|--rpc-url)    shift; export SETH_RPC_URL=$1;;
-
-
-    -f|--from)       shift; export SETH_FROM=$1;;
-    -g|--gas)        shift; export SETH_GAS=$1;;
-       --gas-price)  shift; export SETH_GAS_PRICE;;
-    -v|--value)      shift; export SETH_VALUE;;
-    -b|--block)      shift; export SETH_BLOCK=$1;;
-
-    *)
-      printf "${0##*/}: internal error: %q\n" "$1"
-      exit 1
-  esac
-  shift
-done
-
-if ! [[ $SETH_STARTED ]]; then
-  # Prevent reentry if `~/.sethrc' uses `seth(1)'
-  export SETH_STARTED=1
-
-  if ! which seth-help &>/dev/null; then
-    for dir in ${SETH_LIBEXEC-`dirname $0`/../libexec/seth}/*; do
-      PATH+=:$dir
-    done
-  fi
-
-  : ${SETHRC:=~/.sethrc}
-  if [[ -e $SETHRC ]]; then
-    source $SETHRC
-  fi
+if ! [[ $SETH_INITIALIZED ]]; then
+  export SETH_INITIALIZED=1
+  [[ -e ~/.sethrc ]] && . ~/.sethrc
 fi
 
-for var in SETH_GAS_PRICE SETH_VALUE; do
-  if [[ ${!var} ]]; then
-    export $var=`seth to-wei "${!var}"`
-  fi
-done
+if [[ $2 = --help ]]; then
+  seth help -- "$1"
+elif [[ $1 = -* ]] && program-exists "seth-$1"; then
+  seth-"$@"
+else
+  args=$(getopt -n ${0##*/} -o "${opts[*]}" -l "${optl[*]}" -- "$@")
+  eval set -- $args
 
-exec "seth-${1-help}" "${@:2}"
+  while [[ $1 ]]; do
+    case $1 in
+      --)              shift; break;;
+
+      -h|--rpc-host)   shift; export SETH_RPC_HOST=$1;;
+      -p|--rpc-port)   shift; export SETH_RPC_PORT=$1;;
+      -u|--rpc-url)    shift; export SETH_RPC_URL=$1;;
+
+
+      -f|--from)       shift; export SETH_FROM=$1;;
+      -g|--gas)        shift; export SETH_GAS=$1;;
+         --gas-price)  shift; export SETH_GAS_PRICE;;
+      -v|--value)      shift; export SETH_VALUE;;
+
+      -b|--block)      shift; export SETH_BLOCK=$1;;
+
+      *)
+        printf "${0##*/}: internal error: %q\n" "$1"
+        exit 1
+    esac
+    shift
+  done
+
+  exec "seth-${1-help}" "${@:2}"
+fi
