remove --silent option

diff --git a/libexec/seth/seth-send b/libexec/seth/seth-send
--- a/libexec/seth/seth-send
+++ b/libexec/seth/seth-send
@@ -50,22 +50,16 @@ tx=$(seth --jsonrpc eth_sendTransaction "${jshon[@]}")
 
 [[ $SETH_WAIT = no ]] && exec echo "$tx"
 
-info() { [[ $SETH_SILENT ]] || echo >&2 "$@"; }
-
 bytes=$((${#DATA} - 2))
-info "${0##*/}: Published transaction with $bytes bytes of calldata."
-info "${0##*/}: $tx"
+echo >&2 "${0##*/}: Published transaction with $bytes bytes of calldata."
+echo >&2 "${0##*/}: $tx"
+echo >&2 -n "${0##*/}: Waiting for transaction receipt..."
+number=$(SETH_TICK=true seth receipt "$tx" blockNumber)
+echo >&2
 
-info -n "${0##*/}: Waiting for transaction receipt..."
-[[ $SETH_SILENT ]] || export SETH_TICK=true
-number=$(seth receipt "$tx" blockNumber)
-info
-
-info "${0##*/}: Transaction included in block $number."
+echo >&2 "${0##*/}: Transaction included in block $number."
 [[ $TO ]] || exec seth receipt "$tx" contractAddress
 
-# Warning: Guessing the return value of the transaction by performing the
-# equivalent call on the previous block will produce incorrect results
-# when multiple conflicting transactions are included in the same block.
-[[ $SETH_GUESS_RETURN ]] && info "${0##*/}: note: return value may be inaccurate"
-[[ $SETH_GUESS_RETURN ]] && seth -B "$((number - 1))" call "$TO" "${@:2}"
+[[ $SETH_GUESS_RETURN ]] || exit
+echo >&2 "${0##*/}: warning: return value may be inaccurate"
+seth -B "$((number - 1))" call "$TO" "${@:2}"
