miscellaneous improvements

diff --git a/libexec/seth/seth---to-hexdata b/libexec/seth/seth---to-hexdata
--- a/libexec/seth/seth---to-hexdata
+++ b/libexec/seth/seth---to-hexdata
@@ -12,6 +12,6 @@ elif [[ $1 =~ ^[[:xdigit:]]+$ ]]; then
   echo "0x${1,,}"
 else
   first=${1:0:20} rest=${1:21}
-  echo >&2 "${0##*/}: error: invalid hexdata: \`$first${rest:+...}'"
+  echo >&2 "${0##*/}: error: invalid hexdata: \`$1'"
   exit 1
 fi
diff --git a/libexec/seth/seth-receipt b/libexec/seth/seth-receipt
--- a/libexec/seth/seth-receipt
+++ b/libexec/seth/seth-receipt
@@ -1,16 +1,26 @@
 #!/usr/bin/env bash
-### seth-receipt -- wait for a transaction receipt to appear and print it
-### Usage: seth receipt [-a|--async] <tx-hash>
-### Print the transaction receipt corresponding to <tx-hash>.
-### Unless `-a' is given, wait indefinitely for the receipt to appear.
 set -e
+### seth-receipt -- wait for a transaction receipt to appear and print it
+### Usage: seth receipt [-a|--async] <tx-hash> [<field>]
+error() { echo >&2 "${##*/}: error: $*"; exit 1; }
+
+### Print information about the transaction receipt for <tx-hash>.
 tx=$(seth --to-hexdata "${1?missing transaction hash}")
 jshon+=(-s "$tx" -i append)
-result=$(seth --jsonrpc eth_getTransactionReceipt "${jshon[@]}")
-[[ $result != null ]] && block=$(seth --field "$2" <<<"$result" blockNumber)
-[[ ${block-null} != null && $2 ]] && exec seth --field "$2" <<<"$result"
-[[ ${block-null} != null ]] && exec echo "$result"
-[[ $SETH_ASYNC ]] && { echo >&2 "${0##*/}: error: unknown: $tx"; exit 1; }
+
+receipt=$(seth --jsonrpc eth_getTransactionReceipt "${jshon[@]}")
+if [[ $receipt != null ]]
+then blockNumber=$(seth --field "$2" <<<"$receipt" blockNumber); fi
+
+### If <field> is given, print only that piece of information.
+if [[ ${blockNumber-null} != null && $2 ]]
+then exec seth --field "$2" <<<"$receipt"; fi
+### If no <field> is given, print the whole transaction receipt.
+if [[ ${blockNumber-null} != null ]]
+then exec echo "$receipt"; fi
+
+### Unless `-a' is given, wait indefinitely for the receipt to appear.
+[[ $SETH_ASYNC ]] && error "not found: $tx"
 sleep 1
 [[ $SETH_TICK ]] && printf . >&2
 exec "$0" "$@"
diff --git a/libexec/seth/seth-send b/libexec/seth/seth-send
--- a/libexec/seth/seth-send
+++ b/libexec/seth/seth-send
@@ -20,6 +20,11 @@ jshon+=(-s "$data" -i data)
 
 jshon+=($(seth --send-params))
 tx=$(seth --jsonrpc eth_sendTransaction -n {} "${jshon[@]}" -i append)
+if [[ $tx =~ ^0x0*$ ]]; then
+   echo >&2 "${0##*/}: error: bad tx hash: $tx"
+   echo >&2 "${0##*/}: is your account locked?"
+   exit 1
+fi
 
 ###
 ### If `-a' is given, just print the transaction hash and exit immediately.
@@ -30,9 +35,9 @@ info() if ! [[ $SETH_SILENT ]]; then echo >&2 "$@"; fi
 info "${0##*/}: $tx"
 info -n "${0##*/}: Waiting for transaction receipt..."
 [[ $SETH_SILENT ]] || export SETH_TICK=true
-number=$(seth receipt "$tx" blockNumber)
+n=$(seth receipt "$tx" blockNumber)
 info
-info "${0##*/}: Transaction included in block $number."
+info "${0##*/}: Transaction included in block $n."
 
 ### If no <object> was given, print the address of the newly created object.
 [[ $object ]] || exec seth receipt "$tx" contractAddress
@@ -40,7 +45,7 @@ info "${0##*/}: Transaction included in block $number."
 ### If <object> was given, print the "inferred" return value of the call.
 ### Warning: return value may be wrong in case of conflicting transactions.
 info "${0##*/}: \
-warning: return value may be inaccurate (see \`seth send --help')"
+note: return value may be inaccurate (see \`seth send --help')"
 
 # XXX: Inferring the return value of the transaction by performing the
 # equivalent call on the previous block can produce incorrect results
