lots of improvements

diff --git a/libexec/seth/seth---jsonrpc b/libexec/seth/seth---jsonrpc
--- a/libexec/seth/seth---jsonrpc
+++ b/libexec/seth/seth---jsonrpc
@@ -9,10 +9,9 @@ response=`seth --jsonrpc-curl <<<"$request"`
 if result=`jsonrpc-result <<<"$response"`; then
   seth --show-json "$result"
 elif error=`jsonrpc-error <<<"$response"`; then
-  { printf '%q ' "$@"; echo
-    SETH_KEY_WIDTH=10 seth --show-json "$error" |
-    sed 's/^/  /'; } |
-  sed >&2 "s/^/seth: error: /"
+  { echo "$request"
+    SETH_KEY_WIDTH=10 seth --show-json "$error" | sed 's/^/error:   /'
+  } | sed >&2 "s/^/${0##*/}: /"
   exit 1
 else
   echo >&2 "$response"
diff --git a/libexec/seth/seth---to-hexdata b/libexec/seth/seth---to-hexdata
--- a/libexec/seth/seth---to-hexdata
+++ b/libexec/seth/seth---to-hexdata
@@ -1,12 +1,17 @@
 #!/usr/bin/env bash
 set -e
-[[ $1 ]] || set -- "`cat`"
+[[ $2 ]] && { echo >&2 "Usage: ${0##*/} <hexdata>"; exit 1; }
+[[ $1 ]] || set -- "$(cat)"
 
-if [[ $1 =~ ^0x[[:xdigit:]]+$ ]]; then
-  echo ${1,,}
+if [[ $1 = @* ]]; then
+  x=$(seth --lookup "$1")
+  exec "$0" "$x"
+elif [[ $1 =~ ^0x[[:xdigit:]]+$ ]]; then
+  echo "${1,,}"
 elif [[ $1 =~ ^[[:xdigit:]]+$ ]]; then
-  echo 0x${1,,}
-else  
-  echo >&2 "${0##*/}: error: invalid hexdata: \`$1'"
+  echo "0x${1,,}"
+else
+  first=${1:0:20} rest=${1:21}
+  echo >&2 "${0##*/}: error: invalid hexdata: \`$first${rest:+...}'"
   exit 1
 fi
diff --git a/libexec/seth/seth---to-wei b/libexec/seth/seth---to-wei
--- a/libexec/seth/seth---to-wei
+++ b/libexec/seth/seth---to-wei
@@ -1,15 +1,11 @@
 #!/usr/bin/env bash
-set -e
-set -- $*
-set -- ${1?missing amount} ${2-wei}
-
-case ${2,,} in
-  wei)  scale=0;;
-  gwei) scale=9;;
-  eth)  scale=18;;
-  *)
-    echo >&2 "${0##*/}: error: unrecognized money: $*"
-    exit 1
-esac
-
-bc <<<"$1 * 10^$scale / 1"
+error() { echo >&2 "${0##*/}: error: $*"; exit 1; }
+set -- "$*"
+[[ ${1?missing amount} = *\ * ]] || set -- "$1 wei"
+number=${1%% *} unit=${1#* }
+case ${unit,,} in
+wei) scale=0;;
+gwei) scale=9;;
+eth) scale=18;;
+*) error "unrecognized monetary value: \`$1'";; esac
+bc <<<"$number * 10^$scale / 1"
diff --git a/libexec/seth/seth-block b/libexec/seth/seth-block
--- a/libexec/seth/seth-block
+++ b/libexec/seth/seth-block
@@ -1,12 +1,17 @@
 #!/usr/bin/env bash
-set -e
-if [[ $1 ]]; then
-  block=`seth get-block-by-number "$1"`
-  if [[ $2 ]]; then
-    seth --field "$2" <<<"$block"
-  else
-    echo "$block"
-  fi
-else
-  seth syncing
-fi
+### seth-block -- print general or specific information about a block
+### Usage: seth block [<block>] [<field>]
+### Print information about <block> (either a number or the string `latest').
+###
+### If <field> is given, print only that piece of information.
+### If no <field> is given, print all available information about <block>.
+###
+### If no <block> is given, print latest block number and syncing info.
+set -e -o pipefail
+[[ $3 ]] && { seth block --help; exit 1; }
+[[ $1 ]] || exec seth syncing
+result=$(seth get-block-by-number "$1")
+[[ $result != null && $2 ]] && exec seth --field "$2" <<<"$result"
+[[ $result != null ]] && exec echo "$result"
+echo >&2 "${0##*/}: error: no such block: $1"
+exit 1
diff --git a/libexec/seth/seth-send b/libexec/seth/seth-send
--- a/libexec/seth/seth-send
+++ b/libexec/seth/seth-send
@@ -1,21 +1,48 @@
 #!/usr/bin/env bash
 ### seth-send -- sign and publish a transaction to the blockchain
-### Usage: seth send [-f <account>] [-v <value>] [<receiver>] [<calldata>]
-###    or: seth send [-f <account>] [-v <value>] <receiver> <sig> [<args>]
+### Usage: seth send [-a] [-f <origin>] [-v <value>] <object> <sig> [<args>]
+###    or: seth send [-a] [-f <origin>] [-v <value>] [<object>] [<data>]
 ###
-### Publish a transaction to call <receiver> from <account>.
-### If no <receiver> is given, create a new contract instead.
+### Publish a transaction signed by <origin> to call <object> with <data>.
+### If no <object> is given, create a new object (initialized from <data>).
 ###
-### If no <calldata> is given, read it from standard input instead.
-### If no <calldata> is given at all, just transfer <value> to <receiver>.
-
+### If no <origin> is given, fall back to `$SETH_ORIGIN' or `$SETH_FROM'.
+### If no <origin> is given at all, just print an error message and exit.
 set -e
-[[ $1 ]] && receiver=`seth --to-hexdata "$1"`
-calldata=`seth calldata ${2+"${@:2}"}`
-result=$(seth --jsonrpc eth_sendTransaction \
-  -n {}                                     \
-    -s $calldata -i data                    \
-    ${receiver+-s $receiver -i to}          \
-    `seth --send-params`                    \
-  -iappend)
-seth --decode "$2" <<<"$result"
+[[ $1 ]] && object=$(seth --to-address "$1")
+[[ $object ]] && jshon+=(-s "$object" -i to)
+
+###
+### If <sig> has the form `<name>(<types>)', infer <data> from <sig>/<args>.
+### If no <data> is given, read the call data from standard input instead.
+### If no <data> is given at all, just call <object> without any call data.
+data=$(seth calldata ${2+"${@:2}"})
+jshon+=(-s "$data" -i data)
+
+jshon+=($(seth --send-params))
+tx=$(seth --jsonrpc eth_sendTransaction -n {} "${jshon[@]}" -i append)
+
+###
+### If `-a' is given, then print the transaction hash and exit immediately.
+[[ $SETH_ASYNC ]] && exec echo "$tx"
+
+### Otherwise, wait for the transaction receipt and then proceed as follows:
+echo >&2 "${0##*/}: $tx"
+echo -n >&2 "${0##*/}: Waiting for transaction receipt..."
+n=$(SETH_TICK=yes seth receipt "$tx" blockNumber)
+echo >&2
+echo >&2 "${0##*/}: Transaction included in block $n."
+
+###
+### If no <object> is given, print the address of the newly created object.
+[[ $object ]] || exec seth receipt "$tx" contractAddress
+
+### If <object> is given, print the inferred return value of the transaction.
+### Warning: inferred value may be wrong in case of conflicting transactions.
+echo >&2 "${0##*/}: \
+warning: return value may be inaccurate (see \`seth send --help')"
+
+# XXX: Inferring the return value of the transaction by performing the
+# equivalent call on the previous block can produce incorrect results
+# if multiple conflicting transactions are included in the same block.
+seth --block="$((n - 1))" call "$@"
