many changes

diff --git a/libexec/seth/seth b/libexec/seth/seth
--- a/libexec/seth/seth
+++ b/libexec/seth/seth
@@ -10,39 +10,39 @@ set -e
 ###
 ###    -h, --rpc-host=<host>      RPC endpoint host (default: `localhost')
 ###    -p, --rpc-port=<number>    RPC endpoint port (default: `8545')
-###    -u, --rpc-url=<url>        RPC endpoint URL (overrides `-h' and `-p')
-opts+=(h:p:u:)
-optl+=(rpc-host:,rpc-port:,rpc-url:,)
+###        --rpc-url=<url>        RPC endpoint URL (overrides `-h' and `-p')
+opts=(h:p:) optl+=(rpc-host:,rpc-port:,rpc-url:,)
 ###
 ### Transaction options:
 ###
-###    -f, --from=<account>       account to use or send transaction from
-###    -o, --origin=<account>     synonym for `--from'
+###    -F, --from=<origin>        account to use or send transaction from
+###        --origin=<origin>      (synonym for `--from')
 ###
-###    -g, --gas=<number>         number of units of gas to provide
-###        --gas-price=<money>    price of each gas unit (e.g. `20 Gwei')
-###    -v, --value=<money>        amount of money to send (e.g. `0.1 ETH')
-opts+=(f:o:g:v:)
-optl+=(from:,origin:,gas:,gas-price:,value:)
+###    -G, --gas=<number>         number of units of gas to provide
+###        --gas-price=<amount>   price of each gas unit (e.g. `20 Gwei')
+###
+###    -V, --value=<amount>       amount of money to send (e.g. `0.1 ETH')
+opts+=(F:G:V:) optl+=(from:,origin:,gas:,gas-price:,value:)
+###
+### Options for seth-send(1):
+###
+###        --create               use the calldata to create a new object
 ###
 ### Options for seth-send(1) and seth-receipt(1):
 ###
-###    -a, --async                exit after printing transaction hash
-opts+=(a)
+###        --async                exit after printing transaction hash
 optl+=(async)
 ###
 ### Options for seth-call(1), seth-estimate(1) and others:
 ###
 ###    -b, --block=<number>       block number (default: `latest')
-opts+=(b:)
-optl+=(block:,)
+opts+=(b:) optl+=(block:,)
 ###
 ### Other options:
 ###
 ###    -s, --silent               suppress standard error logging output
-###    -q, --quiet                synonym for `--silent'
-opts+=(sq)
-optl+=(silent,quiet)
+###    -q, --quiet                (synonym for `--silent')
+opts+=(sq) optl+=(silent,quiet)
 
 if ! [[ $SETH_INITIALIZED ]]; then
   export SETH_INITIALIZED=true
@@ -50,44 +50,45 @@ if ! [[ $SETH_INITIALIZED ]]; then
 fi
 
 if [[ $2 = --help ]]; then
-  seth help -- "$1"
-elif [[ $1 = -* ]] && which "seth-$1" &>/dev/null; then
-  seth-"$@"
-else
-  args=$(getopt -n ${0##*/} -o "${opts[*]}" -l "${optl[*]}" -- "$@")
-  eval set -- $args
-
-  while [[ $1 ]]; do
-    case $1 in
-      --)              shift; break;;
-
-      -h|--rpc-host)   shift; export SETH_RPC_HOST=$1;;
-      -p|--rpc-port)   shift; export SETH_RPC_PORT=$1;;
-      -u|--rpc-url)    shift; export SETH_RPC_URL=$1;;
-
-
-      -o|--origin)     shift; export SETH_FROM=$1;;
-      -f|--from)       shift; export SETH_FROM=$1;;
-
-      -g|--gas)        shift; export SETH_GAS=$1;;
-         --gas-price)  shift; export SETH_GAS_PRICE;;
-      -v|--value)      shift; export SETH_VALUE=$1;;
-
-      -a|--async)      export SETH_ASYNC=true;;
-
-      -b|--block)      shift; export SETH_BLOCK=$1;;
-
-      -s|--silent)     export SETH_SILENT=true;;
-      -q|--quiet)      export SETH_SILENT=true;;
-
-      *)
-        printf "${0##*/}: internal error: %q\n" "$1"
-        exit 1
-    esac
-    shift
-  done
-
-  export SETH_ORIGIN=${SETH_ORIGIN-${SETH_FROM-$ETH_FROM}}
-
-  exec "seth-${1-help}" "${@:2}"
+  exec "${0##*/}" help -- "$1"
+elif [[ $1 = -* ]] && which "${0##*/}-$1" &>/dev/null; then
+  exec "${0##*/}-$@"
 fi
+
+args=$(getopt -n ${0##*/} -o "${opts[*]}" -l "${optl[*]}" -- "$@")
+eval set -- $args
+
+while [[ $1 ]]; do
+  case $1 in
+    --)              shift; break;;
+
+    -h|--rpc-host)   shift; export SETH_RPC_HOST=$1;;
+    -p|--rpc-port)   shift; export SETH_RPC_PORT=$1;;
+       --rpc-url)    shift; export SETH_RPC_URL=$1;;
+
+
+    -F|--from)       shift; export SETH_FROM=$1;;
+       --origin)     shift; export SETH_FROM=$1;;
+
+    -G|--gas)        shift; export SETH_GAS=$1;;
+       --gas-price)  shift; export SETH_GAS_PRICE;;
+
+    -V|--value)      shift; export SETH_VALUE=$1;;
+
+       --async)      export SETH_ASYNC=true;;
+
+    -b|--block)      shift; export SETH_BLOCK=$1;;
+
+    -s|--silent)     export SETH_SILENT=true;;
+    -q|--quiet)      export SETH_SILENT=true;;
+
+    *) printf "${0##*/}: internal error: %q\n" "$1"; exit 1
+  esac; shift
+done
+
+export SETH_ORIGIN=${SETH_ORIGIN:-${SETH_FROM:-$ETH_FROM}}
+export SETH_RPC_URL=${SETH_RPC_URL:-$ETH_RPC_URL}
+export SETH_RPC_HOST=${SETH_RPC_HOST:-$ETH_RPC_HOST}
+export SETH_RPC_PORT=${SETH_RPC_PORT:-$ETH_RPC_PORT}
+
+"${0##*/}-${1-help}" "${@:2}"
diff --git a/libexec/seth/seth---jsonrpc b/libexec/seth/seth---jsonrpc
--- a/libexec/seth/seth---jsonrpc
+++ b/libexec/seth/seth---jsonrpc
@@ -1,14 +1,21 @@
 #!/usr/bin/env bash
 set -e
+
+version=$(jshon --version) min=20131105
+if [[ $version -lt $min ]]; then
+  echo >&2 "${0##*/}: error: jshon $version is too old (need $min or newer)"
+  exit 1
+fi
+
 jsonrpc-result() { jshon -Q -e result -j; }
-jsonrpc-error()  { jshon -Q -e error -j; }
+jsonrpc-error() { jshon -Q -e error -j; }
 
-request=`seth --jsonrpc-req "$@"`
-response=`seth --jsonrpc-curl <<<"$request"`
+request=$(seth --jsonrpc-req "$@")
+response=$(seth --jsonrpc-curl <<<"$request")
 
-if result=`jsonrpc-result <<<"$response"`; then
+if result=$(jsonrpc-result <<<"$response"); then
   seth --show-json "$result"
-elif error=`jsonrpc-error <<<"$response"`; then
+elif error=$(jsonrpc-error <<<"$response"); then
   { echo "$request"
     SETH_KEY_WIDTH=10 seth --show-json "$error" | sed 's/^/error:   /'
   } | sed >&2 "s/^/${0##*/}: /"
diff --git a/libexec/seth/seth-receipt b/libexec/seth/seth-receipt
--- a/libexec/seth/seth-receipt
+++ b/libexec/seth/seth-receipt
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 set -e
 ### seth-receipt -- wait for a transaction receipt to appear and print it
-### Usage: seth receipt [-a|--async] <tx-hash> [<field>]
-error() { echo >&2 "${##*/}: error: $*"; exit 1; }
+### Usage: seth receipt [--async] <tx-hash> [<field>]
+error() { echo >&2 "${0##*/}: error: $*"; exit 1; }
 
 ### Print information about the transaction receipt for <tx-hash>.
 tx=$(seth --to-hexdata "${1?missing transaction hash}")
@@ -10,7 +10,7 @@ jshon+=(-s "$tx" -i append)
 
 receipt=$(seth --jsonrpc eth_getTransactionReceipt "${jshon[@]}")
 if [[ $receipt != null ]]
-then blockNumber=$(seth --field "$2" <<<"$receipt" blockNumber); fi
+then blockNumber=$(seth --field <<<"$receipt" blockNumber); fi
 
 ### If <field> is given, print only that piece of information.
 if [[ ${blockNumber-null} != null && $2 ]]
@@ -19,7 +19,7 @@ then exec seth --field "$2" <<<"$receipt"; fi
 if [[ ${blockNumber-null} != null ]]
 then exec echo "$receipt"; fi
 
-### Unless `-a' is given, wait indefinitely for the receipt to appear.
+### Unless `--async' is given, wait indefinitely for the receipt to appear.
 [[ $SETH_ASYNC ]] && error "not found: $tx"
 sleep 1
 [[ $SETH_TICK ]] && printf . >&2
diff --git a/libexec/seth/seth-send b/libexec/seth/seth-send
--- a/libexec/seth/seth-send
+++ b/libexec/seth/seth-send
@@ -1,38 +1,42 @@
 #!/usr/bin/env bash
 set -e
 ### seth-send -- sign and publish a transaction to the blockchain
-### Usage: seth send [-a] [-o <origin>] [-v <value>] <object> <sig> [<args>]
-###    or: seth send [-a] [-o <origin>] [-v <value>] [<object>] [<data>]
+### Usage: seth send [-F <origin>] [-V <value>] <object> <sig> [<args>]
+###    or: seth send [-F <origin>] [-V <value>] <object> [<data>]
+###    or: seth send [-F <origin>] [-V <value>] --create <data>
 ###
-### Publish a transaction signed by <origin> to call <object> with <data>.
-### If no <object> is given, create a new object (initialized from <data>).
-### If no <origin> is given, fall back to `$SETH_ORIGIN' or `$SETH_FROM'.
-### If no <origin> is given at all, print an error message and exit.
-[[ $1 ]] && object=$(seth --to-address "$1")
-[[ $object ]] && jshon+=(-s "$object" -i to)
+[[ $1 ]] || { seth help send >&2; exit 1; }
 
+### Publish a transaction (signed by <origin>) to call <object> with <data>.
+### If no <origin> is given, try `$SETH_ORIGIN', `$SETH_FROM' or `$ETH_FROM'.
+### If `--create' is given, create a new object, initialized from <data>.
 ###
+if ! [[ $SETH_CREATE ]]; then
+  object=$(seth --to-address "$1"); shift
+  jshon+=(-s "$object" -i to)
+fi
+
 ### If <sig> has the form `<name>(<types>)', infer <data> from <sig>/<args>.
-### If no <data> is given, read the call data from standard input instead.
-### If no <data> is given at all, just call <object> without any call data.
-data=$(seth calldata ${2+"${@:2}"})
+### If no <data> is given, just call <object> without any call data.
+###
+data=$(seth calldata "$@")
 jshon+=(-s "$data" -i data)
 
 jshon+=($(seth --send-params))
 tx=$(seth --jsonrpc eth_sendTransaction -n {} "${jshon[@]}" -i append)
 
 if [[ $tx =~ ^0x0*$ ]]; then
-   echo >&2 "${0##*/}: error: bad tx hash: $tx"
-   echo >&2 "${0##*/}: sender account: $SETH_ORIGIN"
-   echo >&2 "${0##*/}: make sure sender account is unlocked"
-   exit 1
+  echo >&2 "${0##*/}: error: bad tx hash: $tx"
+  echo >&2 "${0##*/}: origin account: $SETH_ORIGIN"
+  echo >&2 "${0##*/}: make sure account is unlocked"
+  exit 1
 fi
 
+### If `--async' is given, print the transaction hash and exit immediately.
 ###
-### If `-a' is given, just print the transaction hash and exit immediately.
 [[ $SETH_ASYNC ]] && exec echo "$tx"
 
-### Otherwise, wait for the transaction receipt and then proceed as follows:
+### Otherwise, wait for the transaction receipt and then proceed as follows.
 info() if ! [[ $SETH_SILENT ]]; then echo >&2 "$@"; fi
 info "${0##*/}: $tx"
 info -n "${0##*/}: Waiting for transaction receipt..."
@@ -46,13 +50,13 @@ info "${0##*/}: Transaction included in block $n."
 
 ### If <object> was given, print the "inferred" return value of the call.
 ### Warning: return value may be wrong in case of conflicting transactions.
+###
 info "${0##*/}: \
-note: return value may be inaccurate (see \`seth send --help')"
+warning: return value may be inaccurate (see \`seth send --help')"
 
 # XXX: Inferring the return value of the transaction by performing the
 # equivalent call on the previous block can produce incorrect results
 # if multiple conflicting transactions are included in the same block.
-seth --block="$((n - 1))" call "$@"
+seth -b "$((n - 1))" call "$object" "$@"
 
-###
 ### See also seth-receipt(1), seth-call(1), seth-sign(1), seth-send-raw(1).
