seth: add `--chain' option for remote node presets

diff --git a/libexec/seth/seth b/libexec/seth/seth
--- a/libexec/seth/seth
+++ b/libexec/seth/seth
@@ -10,6 +10,7 @@
 ###    --rpc-host=<host>          JSON-RPC host (default: `localhost')
 ###    --rpc-port=<port>          JSON-RPC port (default: `8545')
 ###    --rpc-url=<url>            JSON-RPC URL (overrides host and port)
+###    -C, --chain=<chain>        remote node configuration preset
 ###
 ### Transaction options:
 ###
@@ -43,6 +44,7 @@ seth <command> --help
 rpc-host=host        JSON-RPC host (default: \`localhost')
 rpc-port=port        JSON-RPC port (default: \`8545')
 rpc-url=url          JSON-RPC URL (overrides host and port)
+C,chain=chain        remote node configuration preset
 
   Transaction options:
 F,from=address       account to send transaction from
@@ -90,6 +92,8 @@ while [[ $1 ]]; do
     --rpc-port)      shift; export ETH_RPC_PORT=$1;;
     --rpc-url)       shift; export ETH_RPC_URL=$1;;
 
+    -C|--chain)      shift; export SETH_CHAIN=$1;;
+
     -B|--block)      shift; export ETH_BLOCK=$1;;
     -F|--from)       shift; export ETH_FROM=$1;;
     -G|--gas)        shift; export ETH_GAS=$1;;
@@ -109,5 +113,24 @@ while [[ $1 ]]; do
     *) printf "${0##*/}: internal error: %q\n" "$1"; exit 1
   esac; shift
 done
+
+if [[ $SETH_CHAIN ]]; then
+  export ETH_RPC_URL ETHERSCAN_API_URL
+  export SETH_LOGS_API=${SETH_LOGS_API:-etherscan}
+
+  case "$SETH_CHAIN" in
+    ethlive)
+      ETH_RPC_URL=https://mainnet.infura.io
+      ETHERSCAN_API_URL=https://api.etherscan.io/api
+      ;;
+    ropsten|kovan|rinkeby)
+      ETH_RPC_URL=https://$SETH_CHAIN.infura.io
+      ETHERSCAN_API_URL=https://$SETH_CHAIN.etherscan.io/api
+      ;;
+    *)
+      echo >&2 "${0##*/}: error: unknown chain: \'$SETH_CHAIN'"
+      exit 1
+  esac
+fi
 
 "${0##*/}-${1-help}" "${@:2}"
