dapp testnet: snapshot support, etc.
This makes `dapp testnet` more useful by introducing named snapshots.
It also lets you run a shell command within the testnet environment.
It also improves the configurability of the chain ID, RPC port, etc.

Examples:

  1. Run an ephemeral testnet to run a single seth command:

    $ dapp testnet -- seth age

  2. Create a named testnet snapshot with one transaction:

    $ dapp testnet --save=foo -- seth send -V 1 $guy
    $ dapp testnet --load=foo -- seth balance $guy

  3. Update a testnet snapshot with one more transaction:

    $ dapp testnet --load=foo --save=foo -- seth send -V 1 $guy

diff --git a/libexec/dapp/dapp---testnet-launch b/libexec/dapp/dapp---testnet-launch
--- a/libexec/dapp/dapp---testnet-launch
+++ b/libexec/dapp/dapp---testnet-launch
@@ -1,38 +1,123 @@
 #!/usr/bin/env bash
 set -e
 
-gethdir=$HOME/.dapp/testnet
-chainid=2000
-while true; do
-  if [[ ! -d "$gethdir/$chainid" ]]; then break; fi
-  chainid=$((chainid + 1))
+OPTS="dapp testnet [<options>] <args>...
+dapp testnet --help
+--
+rpc-port=port      change RPC port (default: 8545)
+chain-id=number    change chain ID (default: 99)
+period=seconds     use a block time instead of instamine
+save=name          after finishing, save snapshot
+load=name          start from a previously saved snapshot
+"
+
+eval "$(
+  git rev-parse --parseopt -- "$@" <<<"$OPTS" || echo exit $?
+)"
+
+RPC_PORT=8545
+PERIOD=0
+CHAINID=99
+
+while [[ $1 ]]; do
+  case $1 in
+    --)          shift; break;;
+    --rpc-port)  shift; RPC_PORT=$1;;
+    --chain-id)  shift; CHAINID=$1;;
+    --period)    shift; PERIOD=$1;;
+    --save)      shift; SAVE=$1;;
+    --load)      shift; LOAD=$1;;
+    *) printf "${0##*/}: internal error: $q\n" "$1"; exit 1
+  esac; shift
 done
 
-chaindir="$gethdir/$chainid"
-port=$((chainid + 30000))
+gethdir=$HOME/.dapp/testnet
+chaindir=$gethdir/$RPC_PORT
 
-mkdir -p "$chaindir/config"
+if [[ $LOAD ]]; then
+  mkdir -p "$chaindir"
+  cp -r "$gethdir/snapshots/$LOAD"/{keystore,config} "$chaindir"
+  geth >/dev/null 2>&1 --datadir "$chaindir" init "$chaindir/config/genesis.json"
+  geth >/dev/null 2>&1 --datadir "$chaindir" import "$gethdir/snapshots/$LOAD/backup"
+  address=$(jq <"$chaindir/config/genesis.json" -r ".alloc | keys | .[]")
+  CHAINID=$(jq <"$chaindir/config/genesis.json" -r ".config.chainId")
+else
+  while true; do
+    if [[ ! -d "$gethdir/$CHAINID" ]]; then break; fi
+    CHAINID=$((CHAINID + 1))
+  done
 
-function clean() { ( echo; set -x; rm -rf "$chaindir" ); }
-trap clean EXIT
+  mkdir -p "$chaindir/config"
+  address=$(
+    geth 2>/dev/null account new --datadir "$chaindir" --password=<(exit) 2>/dev/null \
+      | grep Address | sed 's/Address: {\(.*\)}/\1/')
+  jshon >"$chaindir/config/genesis.json" \
+    -n {} \
+    -n {} \
+      -n "$CHAINID" -i chainId \
+      -n 0 -i homesteadBlock \
+      -n 0 -i eip155Block \
+      -n 0 -i eip158Block \
+      -n 0 -i byzantiumBlock \
+      -n {} -n "$PERIOD" -i period -n 3000 -i epoch -i clique \
+      -i config \
+    -s 0x1 -i difficulty \
+    -s 0xffffffffffffffff -i gaslimit \
+    -s "0x3132333400000000000000000000000000000000000000000000000000000000""$address""0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" -i extraData \
+    -n {} \
+      -n {} -s "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" -i balance \
+      -i "$address" \
+    -i alloc
+  geth 2>/dev/null --datadir "$chaindir" init "$chaindir/config/genesis.json"
+fi
 
-address=$(
-  geth 2>/dev/null account new --datadir "$chaindir" --password=<(exit) 2>/dev/null \
-    | grep Address | sed 's/Address: {\(.*\)}/\1/')
+export ETH_RPC_URL=http://127.0.0.1:$RPC_PORT
 
-echo >&2 "dapp-testnet:   Account: $address"
-echo >&2 "dapp-testnet:   RPC URL: http://127.0.0.1:$chainid"
+port=$((RPC_PORT + 30000))
+
+echo >&2 "dapp-testnet:   RPC URL: $ETH_RPC_URL"
 echo >&2 "dapp-testnet:  TCP port: $port"
-echo >&2 "dapp-testnet:  Chain ID: $chainid"
+echo >&2 "dapp-testnet:  Chain ID: $CHAINID"
 echo >&2 "dapp-testnet:  Database: $chaindir"
 echo >&2 "dapp-testnet:  Geth log: $chaindir/geth.log"
 
-echo "$address"                  > "$chaindir/config/account"
-echo "http://127.0.0.1:$chainid" > "$chaindir/config/rpc-url"
-echo "$port"                     > "$chaindir/config/node-port"
+echo "$address"     > "$chaindir/config/account"
+echo "$ETH_RPC_URL" > "$chaindir/config/rpc-url"
+echo "$port"        > "$chaindir/config/node-port"
 
+set +m
 geth \
   2> >(tee "$chaindir/geth.log" | grep --line-buffered Success | sed 's/^/geth: /' >&2) \
-  --datadir "$chaindir" --dev --dev.period "$DAPP_TESTNET_BLOCK_TIME" --networkid "$chainid" --port="$port" \
-  --rpc --rpcapi "web3,eth,debug" --rpccorsdomain '*' --nodiscover \
-  --rpcport="$chainid" --unlock="$address" --password=<(exit)
+  --datadir "$chaindir" --networkid "$CHAINID" --port="$port" \
+  --mine --minerthreads=1 \
+  --rpc --rpcapi "web3,eth,net,debug" --rpccorsdomain '*' --nodiscover \
+  --rpcport="$RPC_PORT" --unlock="$address" --password=<(exit) &
+
+gethpid=$!
+
+clean() {
+  ( set -x; kill -INT $gethpid; wait )
+  if [[ $SAVE ]]; then
+    echo >&2 "dapp-testnet: saving $gethdir/snapshots/$SAVE"
+    mkdir -p "$gethdir/snapshots/$SAVE"
+    cp -r "$chaindir/keystore" "$gethdir/snapshots/$SAVE"
+    cp -r "$chaindir/config" "$gethdir/snapshots/$SAVE"
+    geth >/dev/null 2>^2 --datadir "$chaindir" \
+       export "$gethdir/snapshots/$SAVE/backup"
+  fi
+  ( set -x; rm -rf "$chaindir" )
+}
+trap clean EXIT
+
+until curl -s "$ETH_RPC_URL"; do sleep 1; done
+
+export ETH_FROM=$(seth rpc eth_coinbase)
+export ETH_KEYSTORE=$chaindir/keystore
+export ETH_PASSWORD=/dev/null
+echo >&2 "dapp-testnet:   Account: $ETH_FROM"
+
+if [[ $1 ]]; then
+  "$@"
+else
+  while true; do sleep 3600; done
+fi
