Make dapp test-geth-experimental work for ds-token
Some fixes related to error handling, gas, and balances.

The ds-token tests also need the new Nix version of
"go-ethereum-unlimited" because it removes a limit on code size.

diff --git a/libexec/dapp/dapp-test-geth-experimental b/libexec/dapp/dapp-test-geth-experimental
--- a/libexec/dapp/dapp-test-geth-experimental
+++ b/libexec/dapp/dapp-test-geth-experimental
@@ -31,28 +31,28 @@ testnet=${testnets[0]}
 ETH_FROM=$(cat "$testnet/config/account")
 ETH_RPC_PORT=$(sed 's/^.*://' "$testnet/config/rpc-url")
 ETH_RPC_HOST=127.0.0.1
-ETH_GAS=100000000
+ETH_GAS=$(printf "%d" 0xffffffff)
 export ETH_FROM ETH_RPC_PORT ETH_RPC_HOST ETH_GAS
 
 # We use a temporary directory as a little database.
 tmp=$(mktemp -d)
-clean() { set -x; rm -rf "$tmp"; }
+clean() { rm -rf "$tmp"; }
 trap clean EXIT
 
 # Go through all the contract ABIs and look for ds-test suites.
 for x in $DAPP_OUT/*.abi; do
   contract=$(sed <<<"$(basename "$x")" s/\.abi$//)
-  mkdir "$tmp/$contract"
 
   # Deploy one instance per test method.
   shutup=0
   while read -r method; do
     if [[ $shutup -eq 0 ]]; then
       echo >&2 "dapp-test-geth: deploying test copies for $contract"
+      mkdir "$tmp/$contract"
       shutup=1
     fi
-    { dapp create "$contract" > "$tmp/$contract/$method" 2>/dev/null ; } &
-  done < <(dapp --find-test-methods "$x")
+    dapp create "$contract" >"$tmp/$contract/$method" 2>/dev/null &
+  done < <(dapp --find-test-methods "$x" 2>/dev/null)
   wait
 done
 
@@ -127,21 +127,35 @@ mkcreation() {
 .
 }
 
+failed=0
+
+fail() { echo "FAIL $contract::$method"; touch "$tmp/fail"; }
+pass() { echo "PASS $contract::$method"; }
+
+testcase() {
+  creation=$(mkcreation "$address" "$method")
+  testaddress=$(seth send --create "$creation" --status 2>/dev/null)
+  if seth send "$testaddress" --status 2>/dev/null; then
+    result=$(seth call "$address" 'failed()(bool)')
+    if [[ "$result" == true ]]; then
+      if [[ "$method" == testFail* ]]; then pass; else fail; fi
+    else
+      if [[ "$method" == testFail* ]]; then fail; else pass; fi
+    fi
+  else
+    if [[ "$method" == testFail* ]]; then pass; else fail; fi
+  fi
+}
+
 for contract in "$tmp"/*; do
-  for method in "$contract"/*; do
+  for method in $(printf "%s\n" "$contract"/*); do
     address=$(cat "$method")
     contract=$(basename "$contract")
     method=$(basename "$method")
-    creation=$(mkcreation "$address" "$method")
-    testaddress=$(seth send --create "$creation" --status 2>/dev/null)
-    if seth send "$testaddress" --status 2>/dev/null; then
-      if [[ $(seth call "$address" 'failed()(bool)') == true ]]; then
-        echo "FAIL $contract $method"
-      else
-        echo "PASS $contract $method"
-      fi
-    else
-      echo "FAIL $contract $method"
-    fi
+    testcase &
   done
 done
+
+wait
+
+if [ -e "$tmp/fail" ]; then exit 1; else exit 0; fi
