dapp-test: use hsevm if found

diff --git a/libexec/dapp/dapp-test b/libexec/dapp/dapp-test
--- a/libexec/dapp/dapp-test
+++ b/libexec/dapp/dapp-test
@@ -1,25 +1,13 @@
 #!/usr/bin/env bash
-set -e
-dapp build
+have() { which "$1" >/dev/null 2>&1; }
 
-# compute library addresses as hash(sender, nonce)
-sender="0x00a329c0648769a73afac7f9381e08fb43dbea72"  # ethrun sender
-nonce=1048576  # magic starting nonce
+dapp build || exit
 
-# need to know the names and locations of all of the libraries
-sources=$(find $DAPP_SRC $DAPP_LIB -name '*.sol')
-libraries=$(grep -EH '^library\s+\w+' $sources \
-          | sed -E 's/:library[[:blank:]]+([_[:alnum:]]+)[[:blank:]]+(\{|is).*/:\1/' \
-          | sort)
-links=""
-for lib in $libraries; do
-    address="$(dapp address $sender $nonce)"
-    links="$links $lib:$address"
-    ((nonce++))
-done
-(set -x; solc --link --libraries "$links" $DAPP_OUT/*.bin)
+have hsevm && dapp test-hsevm
+have ethrun && dapp test-ethrun
 
-# pass the library bin files through to ethrun
-# (needs to be exact same order as above for nonces)
-deploy=$(echo "$libraries" | sed -E "s/.*:(.*)/$DAPP_OUT\/\1.bin/")
-(set -x; dapp quicktest "$@" "$DAPP_OUT" $deploy)
+have ethrun || have hsevm || {
+  echo >&2 "${0##*/}: error: neither \`ethrun' nor \`hsevm' found"
+  echo >&2 "${0##*/}: error: please install one (or both) and try again"
+  exit 1
+}
