disallow solc 0.4.9 due to #8

diff --git a/libexec/dapp/dapp b/libexec/dapp/dapp
--- a/libexec/dapp/dapp
+++ b/libexec/dapp/dapp
@@ -4,4 +4,12 @@ export DAPP_LIB=${DAPP_LIB-lib}
 export DAPP_OUT=${DAPP_OUT-out}
 export ROPSTEN_ETHPM_INDEX=0x8011df4830b4f696cd81393997e5371b93338878
 
+version=$(solc --version)
+if echo "$version" | grep -q 0.4.9; then
+  echo >&2 "${0##*/}: error: solc 0.4.9 not supported"
+  echo >&2 "${0##*/}: error: https://github.com/dapphub/dapp/issues/8"
+  echo >&2 "${0##*/}: error: please downgrade to 0.4.8 or upgrade to 0.4.10"
+  exit 1
+fi
+
 "${0##*/}-${1-help}" "${@:2}"
