hevm: count timeouts in test runner

diff --git a/src/hevm/run-blockchain-tests b/src/hevm/run-blockchain-tests
--- a/src/hevm/run-blockchain-tests
+++ b/src/hevm/run-blockchain-tests
@@ -40,11 +40,12 @@ h1, h2 { text-align: center; margin-top: 2rem  }
 #balancefailed .testcase { color: rgb(200, 200, 0) }
 #passed .testcase { color: rgb(0, 150, 0) }
 #skipped .testcase { color: rgb(0, 100, 250) }
+#timeout .testcase { color: rgb(0, 0, 250) }
 </style>
 <header>
 <h1>hevm consensus test report</h1>
 <p>$(date +%Y-%m-%d)</p>
-<p>$(echo "$npass passed, $nbal bad-balance, $nfail failed, $nskip skipped")</p>
+<p>$(echo "$npass passed, $nbal bad-balance, $nfail failed, $nskip skipped, $ntime timeout")</p>
 (Test suite: <span class=GeneralStateTests</span>GeneralStateTests</span> for ConstantinopleFix)
 </header>
 <h2>Failed tests</h2>
@@ -56,6 +57,11 @@ $(echo $failed)
 <table id=balancefailed>
 <tbody>
 $(echo $balancefailed)
+</table>
+<h2>Timeout tests</h2>
+<table id=timeout>
+<tbody>
+$(echo $timeout)
 </table>
 <h2>Skipped tests</h2>
 <table id=skipped>
@@ -96,6 +102,7 @@ shopt -s nocasematch
       bad-balance) balancefailed+=$row ;;
       bad-nonce)   noncefailed+=$row ;;
       bad-storage) storagefailed+=$row ;;
+      timeout)     timeout+=$row ;;
       skip)        skipped+=$row ;;
       *)           failed+=$row ;;
     esac
@@ -108,6 +115,7 @@ shopt -s nocasematch
   nnon=$(sum "$noncefailed")
   nstr=$(sum "$storagefailed")
   nfail=$(sum "$failed")
+  ntime=$(sum "$timeout")
   nskip=$(sum "$skipped")
 
   echo >&2 "passed: $npass"
@@ -115,6 +123,7 @@ shopt -s nocasematch
   echo >&2 "bad-nonce: $nnon"
   echo >&2 "bad-storage: $nstr"
   echo >&2 "failed: $nfail"
+  echo >&2 "timeout: $ntime"
   echo >&2 "skipped: $nskip"
 
   if [[ $html == "True" ]]; then
