hevm: identify bad-storage tests

diff --git a/src/hevm/run-blockchain-tests b/src/hevm/run-blockchain-tests
--- a/src/hevm/run-blockchain-tests
+++ b/src/hevm/run-blockchain-tests
@@ -44,6 +44,7 @@ shopt -s nocasematch
       ok)          passed+=$row ;;
       bad-balance) balancefailed+=$row ;;
       bad-nonce)   noncefailed+=$row ;;
+      bad-storage) storagefailed+=$row ;;
       skip)        skipped+=$row ;;
       *)           failed+=$row ;;
     esac
@@ -52,6 +53,7 @@ shopt -s nocasematch
   npass=$(echo -ne "$passed" | wc -l)
   nbal=$(echo -ne "$balancefailed" | wc -l)
   nnon=$(echo -ne "$noncefailed" | wc -l)
+  nstr=$(echo -ne "$storagefailed" | wc -l)
   nfail=$(echo -ne "$failed" | wc -l)
   nskip=$(echo -ne "$skipped" | wc -l)
 
@@ -127,6 +129,7 @@ $(date +%Y-%m-%d)
   echo >&2 "passed: $npass"
   echo >&2 "bad-balance: $nbal"
   echo >&2 "bad-nonce: $nnon"
+  echo >&2 "bad-storage: $nstr"
   echo >&2 "failed: $nfail"
   echo >&2 "skipped: $nskip"
 }
