seth support for dynamic fee txs (EIP-1559)

diff --git a/src/seth/libexec/seth/seth-mktx b/src/seth/libexec/seth/seth-mktx
--- a/src/seth/libexec/seth/seth-mktx
+++ b/src/seth/libexec/seth/seth-mktx
@@ -17,7 +17,6 @@ args=(
   --from "$(seth --to-address "$ETH_FROM")"
   --nonce "${ETH_NONCE:-$(seth nonce "$ETH_FROM")}"
   --chain-id "$(seth chain-id)"
-  --gas-price "${ETH_GAS_PRICE:-$(seth gas-price)}"
   --gas-limit "${ETH_GAS:-200000}"
   --value "$value"
   --data "${data:-0x}"
@@ -29,6 +28,18 @@ else
   args+=(--to "$(seth --to-address "$1")")
 fi
 
+if [[ $ETH_GAS_PRICE ]]; then
+  args+=(--gas-price "$ETH_GAS_PRICE")
+else if [[ $ETH_PRIO_FEE ]] && [[ $ETH_MAX_FEE ]]; then
+  args+=(--prio-fee "$ETH_PRIO_FEE")
+  args+=(--max-fee "$ETH_MAX_FEE")
+else
+  echo >&2 "required: gas price or (max prio and max fee)"         
+  seth --fail-usage "$0"
+fi
+
+
+   
 if [ -n "$ETH_PASSWORD" ]; then args+=(--passphrase-file "$ETH_PASSWORD"); fi
 
 tx=$([[ $SETH_VERBOSE ]] && set -x; ethsign tx "${args[@]}")
