seth: --verbose,-v flag for debugging

diff --git a/src/seth/libexec/seth/seth-debug b/src/seth/libexec/seth/seth-debug
--- a/src/seth/libexec/seth/seth-debug
+++ b/src/seth/libexec/seth/seth-debug
@@ -48,14 +48,18 @@ for i in "${txs[@]}"; do
   hash=$(<<< "$tx" seth --field hash)
 
   if [[ "$1" = "$hash" ]]; then
-    [[ $j = 0 ]] || echo ""
+    echo -e >&2 "\r${0##*/}: info: transaction ($j/$index)"
     seth run-tx "$tx" --state "$state" --debug "${opts[@]}"
     tidy
     break
   else
-    echo -en >&2 "\r${0##*/}: info: transaction ($j/$index)"
+    [[ $SETH_VERBOSE ]] &&
+      echo -e  >&2 "\r${0##*/}: info: transaction ($j/$index)" ||
+      echo -en >&2 "\r${0##*/}: info: transaction ($j/$index)"
     # exit code 2 means REVERT or otherwise acceptable failure
-    seth run-tx "$tx" --state "$state" --timestamp "$timestamp" > /dev/null || [[ $? == 2 ]] || (tidy; echo ""; seth --fail "${0##*/}: error: hevm error while executing tx: $hash")
+    seth run-tx "$tx" --state "$state" --timestamp "$timestamp" > /dev/null ||
+      [[ $? == 2 ]] ||
+      (tidy; echo ""; seth --fail "${0##*/}: error: hevm error while executing tx: $hash")
     j=$((j + 1))
   fi
 done
