dapp: use solc binaries directly in dapp --use
This is significantly quicker than using `nix run`. We could have
continued using `nix run`, overriding solc with a static binary: this
would have saved on the download size of the non-static solc being used
previously, but still makes a query to the binary caches and fails
on an offline machine.

Important note: the linux static builds do not have z3 enabled, so SMT
checking will no longer work on linux when using `dapp --use solc:x.y.z`.
To use a z3-enabled solc when using `dapp --use` a user will have to install
it and then use it with either

    dapp --use solc ...

where "solc" is the name of the installed binary, or

    dapp --use /path/to/solc ...

or

    DAPP_SOLC=`which solc` dapp ...

The default solc installed by dapptools (and linked to dapp when invoked
without --use) remains as the nixpkgs z3-enabled version, i.e. we will
still do smt builds with

    dapp build

diff --git a/src/dapp/libexec/dapp/dapp---use b/src/dapp/libexec/dapp/dapp---use
--- a/src/dapp/libexec/dapp/dapp---use
+++ b/src/dapp/libexec/dapp/dapp---use
@@ -14,14 +14,21 @@ function usage() {
 
 shopt -s extglob
 case $1 in
+  # package spec e.g. solc:0.4.12
   solc:[0-9].+([0-9.]))
-    version=${1#solc:}
-    version=${version//./_}
-    override+=" solc = solc-versions.solc_$version;"
+    solc="solc-${1#solc:}"
+    set +e
+    bin="$(type -p "$solc")"
+    ;;
+  # some other solc binary name
+  solc*)
+    solc="$1"
+    set +e
+    bin="$(type -p "$solc")"
     ;;
   # if there's a '/', interpret as a path
   */*)
-    export DAPP_SOLC="$1"
+    bin="$1"
     ;;
   *)
     echo >&2 "${0##*/}: unrecognized package spec: $1"
@@ -31,12 +38,14 @@ shift
 
 [[ "$#" -gt 0 ]] || usage
 
-if [ -z "$override" ]; then
-
-dapp "$@"
-
+if [[ -z "$bin" ]]; then
+  echo >&2 "${0##*/}: Could not find ${solc} in your path."
+  echo >&2 "${0##*/}: Try \`nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.$solc\`"
+  echo >&2 "${0##*/}: in your dapptools repo."
+  exit 1
 else
-
-dapp --nix-run "dapp.override {$override}" dapp "$@"
-
+  set -e
+  SOLCBIN="$(realpath -e "${bin}")"
 fi
+
+DAPP_SOLC="$SOLCBIN" dapp "$@"
